/**
 * src/parser/lr_table.h - LR(1) analyze table
 *
 * NOTE: this file is auto-generated by LRAnalyzer.py
 */

#ifndef _LR_ANALYZER_TABLE_H_
#define _LR_ANALYZER_TABLE_H_

#include "lr_reduce.h"

// clang-format off

/**
 * productions:
 *    0: pattern -> term
 *    1: term -> wrap
 *    2: term -> alter
 *    3: term -> join
 *    4: term -> dist
 *    5: term -> ddist
 *    6: term -> anti-anto
 *    7: term -> anti-ambi
 *    8: term -> plain
 *    9: wrap -> ( term )
 *   10: alter -> term | term
 *   11: join -> term term
 *   12: dist -> term . {m,n} term
 *   13: ddist -> term \d {m,n} term
 *   14: anti-anto -> anto term
 *   15: anto -> (?<! term )
 *   16: anti-ambi -> term ambi
 *   17: ambi -> (?&! term )
 *   18: plain -> text
 */

#define LR_PDCT_NUM 19

static const int lr_pdct2nonid[LR_PDCT_NUM] = {
  2, 0, 0, 0, 0, 0, 0, 0, 0, 9, 11, 1, 10, 4, 7, 5, 3, 6, 8, 
};

static const lr_reduce_func lr_reduce_func_table[LR_PDCT_NUM] = {
    NULL,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_unwrap,
    reduce_alter,
    reduce_join,
    reduce_dist,
    reduce_dist,
    reduce_anto,
    reduce_unwrap,
    reduce_ambi,
    reduce_unwrap,
    reduce_text2pure,

};


typedef enum _lr_action {
  deny = 0, // deny
  acpt,     // accept
  shft,     // shift
  rduc      // reduce
} lr_action_e;


typedef struct _lr_table_item {
  lr_action_e action;
  int index;
} lr_item_s, *lr_item_t;


lr_item_s lr_action_table[59][11] = {
/*          TOKEN_TEXT,    TOKEN_EOF,    TOKEN_ERR,   TOKEN_SUBS,   TOKEN_SUBE,   TOKEN_AMBI,   TOKEN_ANTO,    TOKEN_ANY,    TOKEN_NUM,   TOKEN_REPT,    TOKEN_ALT, */
/*   0 */ { { shft,  9 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   1 */ { { shft,  9 }, { acpt, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { shft, 19 }, { shft, 13 }, { shft, 18 }, { shft, 16 }, { deny, -1 }, { shft, 15 },  },
/*   2 */ { { rduc,  4 }, { rduc,  4 }, { deny, -1 }, { rduc,  4 }, { deny, -1 }, { rduc,  4 }, { rduc,  4 }, { rduc,  4 }, { rduc,  4 }, { deny, -1 }, { rduc,  4 },  },
/*   3 */ { { rduc,  8 }, { rduc,  8 }, { deny, -1 }, { rduc,  8 }, { deny, -1 }, { rduc,  8 }, { rduc,  8 }, { rduc,  8 }, { rduc,  8 }, { deny, -1 }, { rduc,  8 },  },
/*   4 */ { { rduc,  7 }, { rduc,  7 }, { deny, -1 }, { rduc,  7 }, { deny, -1 }, { rduc,  7 }, { rduc,  7 }, { rduc,  7 }, { rduc,  7 }, { deny, -1 }, { rduc,  7 },  },
/*   5 */ { { rduc,  5 }, { rduc,  5 }, { deny, -1 }, { rduc,  5 }, { deny, -1 }, { rduc,  5 }, { rduc,  5 }, { rduc,  5 }, { rduc,  5 }, { deny, -1 }, { rduc,  5 },  },
/*   6 */ { { shft,  9 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   7 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   8 */ { { rduc,  6 }, { rduc,  6 }, { deny, -1 }, { rduc,  6 }, { deny, -1 }, { rduc,  6 }, { rduc,  6 }, { rduc,  6 }, { rduc,  6 }, { deny, -1 }, { rduc,  6 },  },
/*   9 */ { { rduc, 18 }, { rduc, 18 }, { deny, -1 }, { rduc, 18 }, { deny, -1 }, { rduc, 18 }, { rduc, 18 }, { rduc, 18 }, { rduc, 18 }, { deny, -1 }, { rduc, 18 },  },
/*  10 */ { { rduc,  1 }, { rduc,  1 }, { deny, -1 }, { rduc,  1 }, { deny, -1 }, { rduc,  1 }, { rduc,  1 }, { rduc,  1 }, { rduc,  1 }, { deny, -1 }, { rduc,  1 },  },
/*  11 */ { { rduc,  3 }, { rduc,  3 }, { deny, -1 }, { rduc,  3 }, { deny, -1 }, { rduc,  3 }, { rduc,  3 }, { rduc,  3 }, { rduc,  3 }, { deny, -1 }, { rduc,  3 },  },
/*  12 */ { { rduc,  2 }, { rduc,  2 }, { deny, -1 }, { rduc,  2 }, { deny, -1 }, { rduc,  2 }, { rduc,  2 }, { rduc,  2 }, { rduc,  2 }, { deny, -1 }, { rduc,  2 },  },
/*  13 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  14 */ { { rduc, 11 }, { rduc, 11 }, { deny, -1 }, { rduc, 11 }, { deny, -1 }, { shft, 19 }, { rduc, 11 }, { rduc, 11 }, { rduc, 11 }, { deny, -1 }, { rduc, 11 },  },
/*  15 */ { { shft,  9 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  16 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 35 }, { deny, -1 },  },
/*  17 */ { { rduc, 16 }, { rduc, 16 }, { deny, -1 }, { rduc, 16 }, { deny, -1 }, { rduc, 16 }, { rduc, 16 }, { rduc, 16 }, { rduc, 16 }, { deny, -1 }, { rduc, 16 },  },
/*  18 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 36 }, { deny, -1 },  },
/*  19 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  20 */ { { rduc, 14 }, { rduc, 14 }, { deny, -1 }, { rduc, 14 }, { deny, -1 }, { shft, 19 }, { rduc, 14 }, { rduc, 14 }, { rduc, 14 }, { deny, -1 }, { rduc, 14 },  },
/*  21 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { shft, 39 }, { shft, 44 }, { shft, 13 }, { shft, 43 }, { shft, 40 }, { deny, -1 }, { shft, 41 },  },
/*  22 */ { { rduc,  4 }, { deny, -1 }, { deny, -1 }, { rduc,  4 }, { rduc,  4 }, { rduc,  4 }, { rduc,  4 }, { rduc,  4 }, { rduc,  4 }, { deny, -1 }, { rduc,  4 },  },
/*  23 */ { { rduc,  8 }, { deny, -1 }, { deny, -1 }, { rduc,  8 }, { rduc,  8 }, { rduc,  8 }, { rduc,  8 }, { rduc,  8 }, { rduc,  8 }, { deny, -1 }, { rduc,  8 },  },
/*  24 */ { { rduc,  7 }, { deny, -1 }, { deny, -1 }, { rduc,  7 }, { rduc,  7 }, { rduc,  7 }, { rduc,  7 }, { rduc,  7 }, { rduc,  7 }, { deny, -1 }, { rduc,  7 },  },
/*  25 */ { { rduc,  5 }, { deny, -1 }, { deny, -1 }, { rduc,  5 }, { rduc,  5 }, { rduc,  5 }, { rduc,  5 }, { rduc,  5 }, { rduc,  5 }, { deny, -1 }, { rduc,  5 },  },
/*  26 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  27 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  28 */ { { rduc,  6 }, { deny, -1 }, { deny, -1 }, { rduc,  6 }, { rduc,  6 }, { rduc,  6 }, { rduc,  6 }, { rduc,  6 }, { rduc,  6 }, { deny, -1 }, { rduc,  6 },  },
/*  29 */ { { rduc, 18 }, { deny, -1 }, { deny, -1 }, { rduc, 18 }, { rduc, 18 }, { rduc, 18 }, { rduc, 18 }, { rduc, 18 }, { rduc, 18 }, { deny, -1 }, { rduc, 18 },  },
/*  30 */ { { rduc,  1 }, { deny, -1 }, { deny, -1 }, { rduc,  1 }, { rduc,  1 }, { rduc,  1 }, { rduc,  1 }, { rduc,  1 }, { rduc,  1 }, { deny, -1 }, { rduc,  1 },  },
/*  31 */ { { rduc,  3 }, { deny, -1 }, { deny, -1 }, { rduc,  3 }, { rduc,  3 }, { rduc,  3 }, { rduc,  3 }, { rduc,  3 }, { rduc,  3 }, { deny, -1 }, { rduc,  3 },  },
/*  32 */ { { rduc,  2 }, { deny, -1 }, { deny, -1 }, { rduc,  2 }, { rduc,  2 }, { rduc,  2 }, { rduc,  2 }, { rduc,  2 }, { rduc,  2 }, { deny, -1 }, { rduc,  2 },  },
/*  33 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { shft, 47 }, { shft, 44 }, { shft, 13 }, { shft, 43 }, { shft, 40 }, { deny, -1 }, { shft, 41 },  },
/*  34 */ { { rduc, 10 }, { rduc, 10 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { shft, 19 }, { shft, 13 }, { shft, 18 }, { shft, 16 }, { deny, -1 }, { rduc, 10 },  },
/*  35 */ { { shft,  9 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  36 */ { { shft,  9 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  37 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { shft, 50 }, { shft, 44 }, { shft, 13 }, { shft, 43 }, { shft, 40 }, { deny, -1 }, { shft, 41 },  },
/*  38 */ { { rduc, 11 }, { deny, -1 }, { deny, -1 }, { rduc, 11 }, { rduc, 11 }, { shft, 44 }, { rduc, 11 }, { rduc, 11 }, { rduc, 11 }, { deny, -1 }, { rduc, 11 },  },
/*  39 */ { { rduc,  9 }, { rduc,  9 }, { deny, -1 }, { rduc,  9 }, { deny, -1 }, { rduc,  9 }, { rduc,  9 }, { rduc,  9 }, { rduc,  9 }, { deny, -1 }, { rduc,  9 },  },
/*  40 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 51 }, { deny, -1 },  },
/*  41 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  42 */ { { rduc, 16 }, { deny, -1 }, { deny, -1 }, { rduc, 16 }, { rduc, 16 }, { rduc, 16 }, { rduc, 16 }, { rduc, 16 }, { rduc, 16 }, { deny, -1 }, { rduc, 16 },  },
/*  43 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 53 }, { deny, -1 },  },
/*  44 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  45 */ { { rduc, 14 }, { deny, -1 }, { deny, -1 }, { rduc, 14 }, { rduc, 14 }, { shft, 44 }, { rduc, 14 }, { rduc, 14 }, { rduc, 14 }, { deny, -1 }, { rduc, 14 },  },
/*  46 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { shft, 55 }, { shft, 44 }, { shft, 13 }, { shft, 43 }, { shft, 40 }, { deny, -1 }, { shft, 41 },  },
/*  47 */ { { rduc, 15 }, { deny, -1 }, { deny, -1 }, { rduc, 15 }, { deny, -1 }, { deny, -1 }, { rduc, 15 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  48 */ { { rduc, 13 }, { rduc, 13 }, { deny, -1 }, { rduc, 13 }, { deny, -1 }, { shft, 19 }, { rduc, 13 }, { rduc, 13 }, { rduc, 13 }, { deny, -1 }, { rduc, 13 },  },
/*  49 */ { { rduc, 12 }, { rduc, 12 }, { deny, -1 }, { rduc, 12 }, { deny, -1 }, { shft, 19 }, { rduc, 12 }, { rduc, 12 }, { rduc, 12 }, { deny, -1 }, { rduc, 12 },  },
/*  50 */ { { rduc, 17 }, { rduc, 17 }, { deny, -1 }, { rduc, 17 }, { deny, -1 }, { rduc, 17 }, { rduc, 17 }, { rduc, 17 }, { rduc, 17 }, { deny, -1 }, { rduc, 17 },  },
/*  51 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  52 */ { { rduc, 10 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { rduc, 10 }, { shft, 44 }, { shft, 13 }, { shft, 43 }, { shft, 40 }, { deny, -1 }, { rduc, 10 },  },
/*  53 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  54 */ { { shft, 29 }, { deny, -1 }, { deny, -1 }, { shft, 27 }, { shft, 58 }, { shft, 44 }, { shft, 13 }, { shft, 43 }, { shft, 40 }, { deny, -1 }, { shft, 41 },  },
/*  55 */ { { rduc,  9 }, { deny, -1 }, { deny, -1 }, { rduc,  9 }, { rduc,  9 }, { rduc,  9 }, { rduc,  9 }, { rduc,  9 }, { rduc,  9 }, { deny, -1 }, { rduc,  9 },  },
/*  56 */ { { rduc, 13 }, { deny, -1 }, { deny, -1 }, { rduc, 13 }, { rduc, 13 }, { shft, 44 }, { rduc, 13 }, { rduc, 13 }, { rduc, 13 }, { deny, -1 }, { rduc, 13 },  },
/*  57 */ { { rduc, 12 }, { deny, -1 }, { deny, -1 }, { rduc, 12 }, { rduc, 12 }, { shft, 44 }, { rduc, 12 }, { rduc, 12 }, { rduc, 12 }, { deny, -1 }, { rduc, 12 },  },
/*  58 */ { { rduc, 17 }, { deny, -1 }, { deny, -1 }, { rduc, 17 }, { rduc, 17 }, { rduc, 17 }, { rduc, 17 }, { rduc, 17 }, { rduc, 17 }, { deny, -1 }, { rduc, 17 },  },
};


lr_item_s lr_goto_table[59][12] = {
/*   0 */ { { shft,  1 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { deny, -1 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*   1 */ { { shft, 14 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { shft, 17 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*   2 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   3 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   4 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   5 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   6 */ { { shft, 20 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { deny, -1 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*   7 */ { { shft, 21 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*   8 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   9 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  10 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  11 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  12 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  13 */ { { shft, 33 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  14 */ { { shft, 14 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { shft, 17 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  15 */ { { shft, 34 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { deny, -1 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  16 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  17 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  18 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  19 */ { { shft, 37 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  20 */ { { shft, 14 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { shft, 17 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  21 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  22 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  23 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  24 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  25 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  26 */ { { shft, 45 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  27 */ { { shft, 46 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  28 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  29 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  30 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  31 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  32 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  33 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  34 */ { { shft, 14 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { shft, 17 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  35 */ { { shft, 48 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { deny, -1 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  36 */ { { shft, 49 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { deny, -1 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  37 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  38 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  39 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  40 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  41 */ { { shft, 52 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  42 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  43 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  44 */ { { shft, 54 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  45 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  46 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  47 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  48 */ { { shft, 14 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { shft, 17 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  49 */ { { shft, 14 }, { shft, 11 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { shft,  6 }, { shft, 17 }, { shft,  8 }, { shft,  3 }, { shft, 10 }, { shft,  2 }, { shft, 12 },  },
/*  50 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  51 */ { { shft, 56 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  52 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  53 */ { { shft, 57 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { deny, -1 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  54 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  55 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  56 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  57 */ { { shft, 38 }, { shft, 31 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { shft, 26 }, { shft, 42 }, { shft, 28 }, { shft, 23 }, { shft, 30 }, { shft, 22 }, { shft, 32 },  },
/*  58 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
};

// clang-format on

#endif  // _LR_ANALYZER_TABLE_H_
