/**
 * src/lr_table.h - LR(1) analyze table
 *
 * NOTE: this file is auto-generated by LRAnalyzer.py
 */

#ifndef _LR_ANALYZER_TABLE_H_
#define _LR_ANALYZER_TABLE_H_

#include "lr_reduce.h"

// clang-format off

/**
 * productions:
 *    0: pattern -> term
 *    1: term -> wrap
 *    2: term -> alter
 *    3: term -> dist
 *    4: term -> anti-anto
 *    5: term -> anti-ambi
 *    6: term -> plain
 *    7: wrap -> ( term )
 *    8: alter -> term | term
 *    9: dist -> term .{m,n} term
 *   10: anti-anto -> anto term
 *   11: anto -> (?<! term )
 *   12: anti-ambi -> term ambi
 *   13: ambi -> (?&! term )
 *   14: plain -> text
 */

#define LR_PDCT_NUM 15

static const int lr_pdct2nonid[LR_PDCT_NUM] = {
  2, 0, 0, 0, 0, 0, 0, 8, 9, 1, 6, 4, 3, 5, 7, 
};

static const lr_reduce_func lr_reduce_func_table[LR_PDCT_NUM] = {
    NULL,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_unwrap,
    reduce_alter,
    reduce_dist,
    reduce_anto,
    reduce_unwrap,
    reduce_ambi,
    reduce_unwrap,
    reduce_text2pure,

};


typedef enum _lr_action {
  deny = 0, // deny
  acpt,     // accept
  shft,     // shift
  rduc      // reduce
} lr_action_e;


typedef struct _lr_table_item {
  lr_action_e action;
  int index;
} lr_item_s, *lr_item_t;


lr_item_s lr_action_table[45][9] = {
/*          TOKEN_TEXT,    TOKEN_EOF,    TOKEN_ERR,   TOKEN_SUBS,   TOKEN_SUBE,   TOKEN_AMBI,   TOKEN_ANTO,   TOKEN_DIST,    TOKEN_ALT, */
/*   0 */ { { shft,  3 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*   1 */ { { deny, -1 }, { acpt, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { shft, 15 }, { shft, 14 },  },
/*   2 */ { { deny, -1 }, { rduc,  3 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  3 }, { deny, -1 }, { rduc,  3 }, { rduc,  3 },  },
/*   3 */ { { deny, -1 }, { rduc, 14 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 14 }, { deny, -1 }, { rduc, 14 }, { rduc, 14 },  },
/*   4 */ { { deny, -1 }, { rduc,  5 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  5 }, { deny, -1 }, { rduc,  5 }, { rduc,  5 },  },
/*   5 */ { { shft,  3 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*   6 */ { { deny, -1 }, { rduc,  4 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  4 }, { deny, -1 }, { rduc,  4 }, { rduc,  4 },  },
/*   7 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*   8 */ { { deny, -1 }, { rduc,  1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  1 }, { deny, -1 }, { rduc,  1 }, { rduc,  1 },  },
/*   9 */ { { deny, -1 }, { rduc,  2 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  2 }, { deny, -1 }, { rduc,  2 }, { rduc,  2 },  },
/*  10 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  11 */ { { deny, -1 }, { rduc,  6 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  6 }, { deny, -1 }, { rduc,  6 }, { rduc,  6 },  },
/*  12 */ { { deny, -1 }, { rduc, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 12 }, { deny, -1 }, { rduc, 12 }, { rduc, 12 },  },
/*  13 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  14 */ { { shft,  3 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  15 */ { { shft,  3 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  16 */ { { deny, -1 }, { rduc, 10 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { rduc, 10 }, { rduc, 10 },  },
/*  17 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 31 }, { shft, 33 }, { deny, -1 }, { shft, 35 }, { shft, 34 },  },
/*  18 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  3 }, { rduc,  3 }, { deny, -1 }, { rduc,  3 }, { rduc,  3 },  },
/*  19 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  20 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  5 }, { rduc,  5 }, { deny, -1 }, { rduc,  5 }, { rduc,  5 },  },
/*  21 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  22 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  4 }, { rduc,  4 }, { deny, -1 }, { rduc,  4 }, { rduc,  4 },  },
/*  23 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 14 }, { rduc, 14 }, { deny, -1 }, { rduc, 14 }, { rduc, 14 },  },
/*  24 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  1 }, { rduc,  1 }, { deny, -1 }, { rduc,  1 }, { rduc,  1 },  },
/*  25 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  2 }, { rduc,  2 }, { deny, -1 }, { rduc,  2 }, { rduc,  2 },  },
/*  26 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  6 }, { rduc,  6 }, { deny, -1 }, { rduc,  6 }, { rduc,  6 },  },
/*  27 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 38 }, { shft, 33 }, { deny, -1 }, { shft, 35 }, { shft, 34 },  },
/*  28 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 39 }, { shft, 33 }, { deny, -1 }, { shft, 35 }, { shft, 34 },  },
/*  29 */ { { deny, -1 }, { rduc,  8 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { shft, 15 }, { rduc,  8 },  },
/*  30 */ { { deny, -1 }, { rduc,  9 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { rduc,  9 }, { rduc,  9 },  },
/*  31 */ { { deny, -1 }, { rduc,  7 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  7 }, { deny, -1 }, { rduc,  7 }, { rduc,  7 },  },
/*  32 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 12 }, { rduc, 12 }, { deny, -1 }, { rduc, 12 }, { rduc, 12 },  },
/*  33 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  34 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  35 */ { { shft, 23 }, { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 },  },
/*  36 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 43 }, { shft, 33 }, { deny, -1 }, { shft, 35 }, { shft, 34 },  },
/*  37 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 10 }, { shft, 33 }, { deny, -1 }, { rduc, 10 }, { rduc, 10 },  },
/*  38 */ { { rduc, 11 }, { deny, -1 }, { deny, -1 }, { rduc, 11 }, { deny, -1 }, { deny, -1 }, { rduc, 11 }, { deny, -1 }, { deny, -1 },  },
/*  39 */ { { deny, -1 }, { rduc, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 13 }, { deny, -1 }, { rduc, 13 }, { rduc, 13 },  },
/*  40 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 44 }, { shft, 33 }, { deny, -1 }, { shft, 35 }, { shft, 34 },  },
/*  41 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  8 }, { shft, 33 }, { deny, -1 }, { shft, 35 }, { rduc,  8 },  },
/*  42 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  9 }, { shft, 33 }, { deny, -1 }, { rduc,  9 }, { rduc,  9 },  },
/*  43 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  7 }, { rduc,  7 }, { deny, -1 }, { rduc,  7 }, { rduc,  7 },  },
/*  44 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 13 }, { rduc, 13 }, { deny, -1 }, { rduc, 13 }, { rduc, 13 },  },
};


lr_item_s lr_goto_table[45][10] = {
/*   0 */ { { shft,  1 }, { shft,  2 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { deny, -1 }, { shft,  6 }, { shft, 11 }, { shft,  8 }, { shft,  9 },  },
/*   1 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   2 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   3 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   4 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   5 */ { { shft, 16 }, { shft,  2 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { deny, -1 }, { shft,  6 }, { shft, 11 }, { shft,  8 }, { shft,  9 },  },
/*   6 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   7 */ { { shft, 17 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*   8 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   9 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  10 */ { { shft, 27 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  11 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  12 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  13 */ { { shft, 28 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  14 */ { { shft, 29 }, { shft,  2 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { deny, -1 }, { shft,  6 }, { shft, 11 }, { shft,  8 }, { shft,  9 },  },
/*  15 */ { { shft, 30 }, { shft,  2 }, { deny, -1 }, { shft,  4 }, { shft,  5 }, { deny, -1 }, { shft,  6 }, { shft, 11 }, { shft,  8 }, { shft,  9 },  },
/*  16 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  17 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  18 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  19 */ { { shft, 36 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  20 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  21 */ { { shft, 37 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  22 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  23 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  24 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  25 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  26 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  27 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  28 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  29 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  30 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  31 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  32 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  33 */ { { shft, 40 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  34 */ { { shft, 41 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  35 */ { { shft, 42 }, { shft, 18 }, { deny, -1 }, { shft, 20 }, { shft, 21 }, { deny, -1 }, { shft, 22 }, { shft, 26 }, { shft, 24 }, { shft, 25 },  },
/*  36 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  37 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  38 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  39 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  40 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  41 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  42 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  43 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  44 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
};

// clang-format on

#endif  // _LR_ANALYZER_TABLE_H_
