/**
 * src/lr_table.h - LR(1) analyze table
 *
 * NOTE: this file is auto-generated by LRAnalyzer
 */

#ifndef _LR_ANALYZER_TABLE_H_
#define _LR_ANALYZER_TABLE_H_

#include "lr_reduce.h"


/**
 * productions:
 *    0: pattern -> term
 *    1: term -> dist
 *    2: term -> anto
 *    3: term -> alter
 *    4: dist -> term3 .{m,n} term3
 *    5: term3 -> anto
 *    6: term3 -> term2
 *    7: term3 -> ambi
 *    8: anto -> anti-anto term2
 *    9: term2 -> ( alter )
 *   10: term2 -> term0
 *   11: alter -> alter | term1
 *   12: alter -> term1
 *   13: term1 -> ambi
 *   14: term1 -> term0
 *   15: ambi -> term0 anti-ambi
 *   16: anti-anto -> (?<! alter0 )
 *   17: anti-ambi -> (?&! alter0 )
 *   18: alter0 -> alter0 | term0
 *   19: alter0 -> term0
 *   20: term0 -> text
 */

#define LR_PDCT_NUM 21

static const int lr_pdct2nonid[LR_PDCT_NUM] = {
  5, 0, 0, 0, 1, 10, 10, 10, 7, 2, 2, 11, 11, 3, 3, 8, 9, 6, 12, 12, 4, 
};

static const lr_reduce_func lr_reduce_func_table[LR_PDCT_NUM] = {
    NULL,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_dist,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_anto,
    reduce_unwrap,
    reduce_only_pop,
    reduce_alter,
    reduce_only_pop,
    reduce_only_pop,
    reduce_only_pop,
    reduce_ambi,
    reduce_unwrap,
    reduce_unwrap,
    reduce_alter,
    reduce_only_pop,
    reduce_text2pure,

};


typedef enum _lr_action {
  deny = 0, // deny
  acpt,     // accept
  shft,     // shift
  rduc      // reduce
} lr_action_e;


typedef struct _lr_table_item {
  lr_action_e action;
  int index;
} lr_item_s, *lr_item_t;


lr_item_s lr_action_table[69][9] = {
/*          TOKEN_TEXT,    TOKEN_EOF,    TOKEN_ERR,   TOKEN_SUBS,   TOKEN_SUBE,   TOKEN_AMBI,   TOKEN_ANTO,   TOKEN_DIST,    TOKEN_ALT, */
/*   0 */ { { shft,  6 }, { deny, -1 }, { deny, -1 }, { shft, 10 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 },  },
/*   1 */ { { deny, -1 }, { acpt, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   2 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 14 }, { deny, -1 },  },
/*   3 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  6 }, { deny, -1 },  },
/*   4 */ { { deny, -1 }, { rduc, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 12 },  },
/*   5 */ { { deny, -1 }, { rduc, 14 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 15 }, { deny, -1 }, { rduc, 10 }, { rduc, 14 },  },
/*   6 */ { { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 }, { deny, -1 }, { rduc, 20 }, { rduc, 20 },  },
/*   7 */ { { deny, -1 }, { rduc,  2 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  5 }, { deny, -1 },  },
/*   8 */ { { deny, -1 }, { rduc, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  7 }, { rduc, 13 },  },
/*   9 */ { { shft, 18 }, { deny, -1 }, { deny, -1 }, { shft, 17 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  10 */ { { shft, 22 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  11 */ { { deny, -1 }, { rduc,  1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  12 */ { { deny, -1 }, { rduc,  3 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 26 },  },
/*  13 */ { { shft, 27 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  14 */ { { shft, 33 }, { deny, -1 }, { deny, -1 }, { shft, 37 }, { deny, -1 }, { deny, -1 }, { shft, 13 }, { deny, -1 }, { deny, -1 },  },
/*  15 */ { { shft, 27 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  16 */ { { deny, -1 }, { rduc, 15 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 15 }, { rduc, 15 },  },
/*  17 */ { { shft, 22 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  18 */ { { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 }, { deny, -1 },  },
/*  19 */ { { deny, -1 }, { rduc,  8 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  8 }, { deny, -1 },  },
/*  20 */ { { deny, -1 }, { rduc, 10 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 10 }, { deny, -1 },  },
/*  21 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 13 },  },
/*  22 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { rduc, 20 },  },
/*  23 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 40 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 41 },  },
/*  24 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 12 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 12 },  },
/*  25 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 14 }, { shft, 42 }, { deny, -1 }, { deny, -1 }, { rduc, 14 },  },
/*  26 */ { { shft, 44 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  27 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 },  },
/*  28 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 48 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 49 },  },
/*  29 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 19 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 19 },  },
/*  30 */ { { deny, -1 }, { rduc,  4 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  31 */ { { deny, -1 }, { rduc,  6 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  32 */ { { deny, -1 }, { rduc, 10 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 50 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  33 */ { { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  34 */ { { deny, -1 }, { rduc,  5 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  35 */ { { deny, -1 }, { rduc,  7 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  36 */ { { shft, 52 }, { deny, -1 }, { deny, -1 }, { shft, 37 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  37 */ { { shft, 22 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  38 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 56 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 49 },  },
/*  39 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 57 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 41 },  },
/*  40 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  9 }, { deny, -1 },  },
/*  41 */ { { shft, 22 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  42 */ { { shft, 27 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  43 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 15 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 15 },  },
/*  44 */ { { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { rduc, 20 },  },
/*  45 */ { { deny, -1 }, { rduc, 13 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 13 },  },
/*  46 */ { { deny, -1 }, { rduc, 11 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 11 },  },
/*  47 */ { { deny, -1 }, { rduc, 14 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 60 }, { deny, -1 }, { deny, -1 }, { rduc, 14 },  },
/*  48 */ { { rduc, 16 }, { deny, -1 }, { deny, -1 }, { rduc, 16 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  49 */ { { shft, 27 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  50 */ { { shft, 27 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  51 */ { { deny, -1 }, { rduc, 15 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  52 */ { { deny, -1 }, { rduc, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  53 */ { { deny, -1 }, { rduc,  8 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  54 */ { { deny, -1 }, { rduc, 10 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  55 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 64 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 41 },  },
/*  56 */ { { deny, -1 }, { rduc, 17 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 17 }, { rduc, 17 },  },
/*  57 */ { { deny, -1 }, { rduc,  9 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc,  9 }, { deny, -1 },  },
/*  58 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 11 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 11 },  },
/*  59 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 65 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 49 },  },
/*  60 */ { { shft, 27 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  61 */ { { deny, -1 }, { rduc, 15 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 15 },  },
/*  62 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 18 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 18 },  },
/*  63 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 67 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 49 },  },
/*  64 */ { { deny, -1 }, { rduc,  9 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  65 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 17 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 17 },  },
/*  66 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 68 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 49 },  },
/*  67 */ { { deny, -1 }, { rduc, 17 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  68 */ { { deny, -1 }, { rduc, 17 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { rduc, 17 },  },
};


lr_item_s lr_goto_table[69][13] = {
/*   0 */ { { shft,  1 }, { shft, 11 }, { shft,  3 }, { shft,  4 }, { shft,  5 }, { deny, -1 }, { deny, -1 }, { shft,  7 }, { shft,  8 }, { shft,  9 }, { shft,  2 }, { shft, 12 }, { deny, -1 },  },
/*   1 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   2 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   3 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   4 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   5 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 16 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   6 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   7 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   8 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*   9 */ { { deny, -1 }, { deny, -1 }, { shft, 19 }, { deny, -1 }, { shft, 20 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  10 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 21 }, { deny, -1 }, { deny, -1 }, { shft, 23 }, { deny, -1 },  },
/*  11 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  12 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  13 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 29 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 28 },  },
/*  14 */ { { deny, -1 }, { deny, -1 }, { shft, 31 }, { deny, -1 }, { shft, 32 }, { deny, -1 }, { deny, -1 }, { shft, 34 }, { shft, 35 }, { shft, 36 }, { shft, 30 }, { deny, -1 }, { deny, -1 },  },
/*  15 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 29 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 38 },  },
/*  16 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  17 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 21 }, { deny, -1 }, { deny, -1 }, { shft, 39 }, { deny, -1 },  },
/*  18 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  19 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  20 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  21 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  22 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  23 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  24 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  25 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 43 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  26 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 46 }, { shft, 47 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 45 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  27 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  28 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  29 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  30 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  31 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  32 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 51 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  33 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  34 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  35 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  36 */ { { deny, -1 }, { deny, -1 }, { shft, 53 }, { deny, -1 }, { shft, 54 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  37 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 24 }, { shft, 25 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 21 }, { deny, -1 }, { deny, -1 }, { shft, 55 }, { deny, -1 },  },
/*  38 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  39 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  40 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  41 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 58 }, { shft, 25 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 21 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  42 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 29 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 59 },  },
/*  43 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  44 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  45 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  46 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  47 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 61 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  48 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  49 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 62 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  50 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 29 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 63 },  },
/*  51 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  52 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  53 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  54 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  55 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  56 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  57 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  58 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  59 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  60 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 29 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { shft, 66 },  },
/*  61 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  62 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  63 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  64 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  65 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  66 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  67 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
/*  68 */ { { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 }, { deny, -1 },  },
};


#endif //_LR_ANALYZER_TABLE_H_
